version = "1.0"

[main]
name.en = "Configuration panel"
name.fr = "Panneau de configuration"
services = ["__APP__-backend"]

#[main.versions]
#name.en = "Version"
#[main.versions.full_version]
#ask.en = "Install premium and enterprise versions"
#ask.fr = "Installer les versions premium et enterprise"
#type = "boolean"
#default = 0
#help.en = "Premium and enterprise versions features are inly accessible through paid plans. Note: the install and upgrade will be slower. After changing this setting you should trigger a force upgrade of this app by yourself to be effective." 
#help.fr = "Les fonctionnalités des versions premium et enterprise sont accessibles via un abonnement payant. NB: l'installation et la mise à jour seront plus lentes. Après avoir modifié ce paramètre, vous devez déclencher vous-même une mise à jour forcée de l'app pour que le changement soit éffectif." 

[main.stmp]
name.en = "SMTP configuration"
name.fr = "Paramètres SMTP"

[main.stmp.email_smtp]
ask.en = "Activation"
ask.fr = "Activation"
type = "boolean"
bind = "null"
yes = "true"
no = "false"
default = "false"

[main.smtp.from_email]
ask.en = "The email address Baserow will send emails from."
ask.fr = "Adresse d'envoi des messages"
type = "email"
bind = "FROM_EMAIL:__INSTALL_DIR__/__APP__/.env"

[main.smtp.email_smtp_user]
ask.en = "The SMTP user email/id"
ask.fr = "Courriel / id d'utilisateur SMTP"
type = "email"
bind = "EMAIL_SMTP_USER:__INSTALL_DIR__/__APP__/.env"
visible = "email_smtp == true"

[main.smtp.email_smtp_password]
ask.en = "user password or application token"
ask.fr = "Mot de passe ou jeton d’application SMTP."
type = "password"
bind = "EMAIL_SMTP_PASSWORD:__INSTALL_DIR__/__APP__/.env"

[main.smtp.email_smtp_host]
ask.en = "SMTP host"
ask.fr = "Nom d’hôte du serveur SMTP"
type = "string"
bind = "EMAIL_SMTP_HOST:__INSTALL_DIR__/__APP__/.env"

[main.smtp.email_smtp_port]
ask.en = "SMTP port"
ask.fr = "Port du serveur SMTP"
type = "number"
optional = true
bind = "EMAIL_SMTP_PORT:__INSTALL_DIR__/__APP__/.env"



[main.smtp.email_smtp_use_ssl]
ask.en = "Use SSL"
ask.fr = "Activer la connexion SSL."
help.fr = "Ne pas utiliser en même temps que TLS"
help.en = "Do not use with TLS"
type = "boolean"
bind = "null"
yes = "true"
no = "false"

[main.smtp.email_smtp_use_tls]
ask.en = "Use TLS"
ask.fr = "Activer la connexion TLS"
help.fr = "Ne pas utiliser en même temps que SSL"
help.en = "Do not use with TLS"
type = "boolean"
bind = "null"
yes = "true"
no = "false"

[main.smtp.alert]
type = "alert"
ask.en = "Both SSL **and** TLS cannot be selected !"
ask.fr = "SSL **et** TLS ne doivent pas être sélectionnés ensemble !"
style = "danger"
visible = "email_smtp_use_tls == true && email_smtp_use_ssl == true"

#[main.ai]
#name.en = "AI models"
#name.fr = "Modèles AI"

#[main.ai.baserow_ollama_host]
#ask.en = "Server address"
#ask.fr = "Adresse du serveur"
#type = "url"
#bind = "BASEROW_OLLAMA_HOST:__INSTALL_DIR__/__APP__/.env"

#[main.ai.baserow_ollama_models]
#ask.en = "List of models"
#ask.fr = "Liste des modèles"
#help.en = "List of available models, separated by commas"
#help.fr = "Liste des modèles disponibles, séparés par des virgules"
#type = "string"
#bind = "BASEROW_OLLAMA_MODELS:__INSTALL_DIR__/__APP__/.env"

[main.limit_size]
name.en = "Upload limit size"
name.fr = "Téléchargement de fichiers"

[main.limit_size.warning]
ask.fr = "Taille limite pour l'import de fichiers dans Baserow -paramètre reporté dans la conf de NGINX"
ask.en = "Baserow size limit file upload"
type = "alert"
style = "danger"

[main.limit_size.upload_max_size]
ask.fr = "Taille limite pour le téléchargement des fichiers en Mo"
ask.en = "Size limit file upload (Mb)"
type = "number"
bind = "null"



[main.storage]
name.en = "AWS S3 bucket"
name.fr = "AWS S3 bucket"

[main.storage.access_key_id]
ask = "AWS_ACCESS_KEY_ID"
type = "string"
bind = "AWS_ACCESS_KEY_ID:__INSTALL_DIR__/__APP__/.env"

[main.storage.secret_access_key]
ask = "AWS_SECRET_ACCESS_KEY"
type = "string"
bind = "AWS_SECRET_ACCESS_KEY:__INSTALL_DIR__/__APP__/.env"

[main.storage.AWS_STORAGE_BUCKET_NAME]
ask = "AWS_STORAGE_BUCKET_NAME"
type = "string"
bind = "AWS_STORAGE_BUCKET_NAME:__INSTALL_DIR__/__APP__/.env"

[main.storage.AWS_S3_REGION_NAME]
ask = "AWS_S3_REGION_NAME"
type = "string"
bind = "AWS_S3_REGION_NAME:__INSTALL_DIR__/__APP__/.env"

[main.storage.AWS_S3_ENDPOINT_URL]
ask = "AWS_S3_ENDPOINT_URL"
type = "url"
bind = "AWS_S3_ENDPOINT_URL:__INSTALL_DIR__/__APP__/.env"

[main.storage.AWS_S3_CUSTOM_DOMAIN]
ask = "AWS_S3_CUSTOM_DOMAIN"
type = "url"
bind = "AWS_S3_CUSTOM_DOMAIN:__INSTALL_DIR__/__APP__/.env"
