packaging_format = 2

id = "baserow"
name = "Baserow"
description.en = "No-code open source database & application builder"
description.fr = "Application open source de création d’applications et de bases de données sans code"

version = "1.35.3~ynh1"

maintainers = ["otm33GH"]

[upstream]
license = "MIT"
website = "https://baserow.io/"
admindoc = "https://baserow.io/docs/index"
code = "https://github.com/baserow/baserow"

[integration]
yunohost = ">= 12.1.6"
architectures = "all"
helpers_version = "2.1"
multi_instance = false
ldap = true
sso = false

disk = "2000M"
ram.build = "1500M"
ram.runtime = "1500M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"
 
[resources]    
    [resources.sources.main]
    url = "https://github.com/baserow/baserow/archive/refs/tags/1.35.3.tar.gz" 
    sha256 = "1920112c370f9cbb54e6c8d9c56187726fb6724197353bb25601aad4f37ed03d"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
	allow_email = true

    [resources.install_dir]
    
    [install.full_version]
    ask.en = "Do you want to install full version (premium & enterprise) ?"
    ask.fr = "Voulez-vous installer la version complète (premium & enterprise) ?"
    help.en = "Premium and enterprise versions features are inly accessible through paid plans. Note: the install and upgrade will be mucho slower (40')." 
    help.fr = "Les fonctionnalités des versions premium et enterprise sont accessibles via un abonnement payant. NB: l'installation et la mise à jour seront beaucoup plus lentes (40')." 
    type = "boolean"
    default = 0
    
    [resources.permissions]
    main.url = "/"

    [resources.ports.backend]

    [resources.ports.frontend]
    [resources.apt]
    packages = "postgresql redis-server python3-venv python3-pip libpq-dev"

    [resources.data_dir]
    subdirs = ["media"]
    group = "www-data:rx"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "24"
    
